---
version: '3'
services:
  kafka:
    image: landoop/fast-data-dev
    environment:
      ADV_HOST: localhost    # Change to 192.168.99.100 if using Docker Toolbox or leave localhost
      RUNTESTS: 0            # Disable Running tests so the cluster starts faster
      CONNECTORS: jdbc
    ports:
      - "2182:2181"                 # Zookeeper
      - "3030:3030"                 # Landoop UI
      - "8081-8083:8081-8083"       # REST Proxy, Schema Registry, Kafka Connect ports
      - "9581-9585:9581-9585"       # JMX Ports
      - "9092:9092"                 # Kafka Broker